name: Fragile
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: write

jobs:
  fragile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: patchwork-eng/fragile@v1
        with:
          openai_key: ${{ secrets.OPENAI_KEY }}

